services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./server/internal/configs/.env
    ports:
      - "8765:8765"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data: